twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        cats: '@App\Twig\CatsExtension'

when@test:
    twig:
        strict_variables: true